Revert "authentication and rolen in sidebar"
Cozac98/tutorias-front pull request #6
Opened 2024-08-12 17:05 UTC by brendaahumada

This reverts commit 68f6568209aa21968489c44747091f5499f8b693.

2024-08-12 19:19 UTC, Cozac98 requested changes

2024-08-12 19:19 UTC, Cozac98 commented on app/Login/page.tsx
> +                  backgroundColor="#D4CBCB"
aca usa un theme asi no lo hardcodeas a los colores, y tambien cambialo a este => D9D9D9

2024-08-13 01:13 UTC, brendaahumada commented on app/Login/page.tsx
> +                  backgroundColor="#D4CBCB"
no entiendo de que me habkas

2024-08-23 21:56 UTC, brendaahumada commented
Este PR incluye los siguientes cambios:

- Fix: Solucionado un error en la página de LoginPage 
- Update:
  - Actualizado el `customTheme` de Chakra UI.
  - Añadida una imagen de fondo a la página de LoginPage.
- Feature:
  - Implementada la autenticación y roles en el componente Sidebar.

2024-09-02 19:58 UTC, Cozac98 requested changes

2024-09-02 19:58 UTC, Cozac98 commented on app/Login/page.tsx
> +      const response = await fetch(`http://localhost:3000/auth/login`, {
para las peticiones usa axios, create un archivo con las peticiones principales y la url base (sacada del .env) y dsp en cada archivo llamas al metodo y completes con el resto de la ruta. ej aca quedaria una cosa asi
await axiosPost('/auth/login', body)

2024-09-06 21:09 UTC, Cozac98 approved these changes

2024-09-06 21:09 UTC, merged